services:
  tasks-create:
    build:
      context: ./apps/tasks-create
    ports:
      - "3001:3000"
    environment:
      NODE_ENV: production
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USERNAME: postgres
      DB_PASSWORD: password
      DB_NAME: tasks_db
      AUTH_SERVICES_URL: http://auth-service:3000/api
    networks:
      - app-network
    depends_on:
      - postgres
      - auth-service

  tasks-update:
    build:
      context: ./apps/tasks-update
    ports:
      - "3002:3000"
    environment:
      NODE_ENV: production
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USERNAME: postgres
      DB_PASSWORD: password
      DB_NAME: tasks_db
      AUTH_SERVICES_URL: http://auth-service:3000/api
    networks:
      - app-network
    depends_on:
      - postgres
      - auth-service

  tasks-delete:
    build:
      context: ./apps/tasks-delete
    ports:
      - "3003:3000"
    environment:
      NODE_ENV: production
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USERNAME: postgres
      DB_PASSWORD: password
      DB_NAME: tasks_db
      AUTH_SERVICES_URL: http://auth-service:3000/api
    networks:
      - app-network
    depends_on:
      - postgres
      - auth-service

  tasks-read:
    build:
      context: ./apps/tasks-read
    ports:
      - "3004:3000"
    environment:
      NODE_ENV: production
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USERNAME: postgres
      DB_PASSWORD: password
      DB_NAME: tasks_db
      AUTH_SERVICES_URL: http://auth-service:3000/api
    networks:
      - app-network
    depends_on:
      - postgres
      - auth-service

  auth-service:
    build:
      context: ./apps/auth-service
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
      JWT_SECRET: your_jwt_secret
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USERNAME: postgres
      DB_PASSWORD: password
      DB_NAME: tasks_db
    networks:
      - app-network
    depends_on:
      - postgres

  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: tasks_db
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres-data:
